<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNxfiX8B\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNxfiX8B/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNxfiX8B.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNxfiX8B\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNxfiX8B\App_KernelDevDebugContainer([
    'container.build_hash' => 'NxfiX8B',
    'container.build_id' => 'e5584b94',
    'container.build_time' => 1593254802,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNxfiX8B');
